### ISSUE TITLE
Add a HacktoberfestBadge component

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#1]
Hacktoberfest is upon us, and what better way to celebrate then to make it easier for repo maintainers to show the right badge for it? There is no official badge, but Shields.io offers a badge that is recommended by the Hacktoberfest team.

This issue is meant to be a good first issue to get into this repository, and into open source contribution over all, as it will require to touch few existing files and is documented extensively. If this is your first contribution to open source, I encourage you to try this issue. Please note that I will only accept one of the good first issues per person to give as many people as possible the opportunity for a first contribution.

Please read our [contribution guidelines](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

## Describe the solution you'd like

This is what the badge should look like in its most basic form:

![GitHub Hacktoberfest combined status](https://img.shields.io/github/hacktoberfest/2020/dbartholomae/jsx-readme)

It should be accessible as `<HacktoberfestBadge year={2020} />`, with an optional prop `suggestionLabel` that can be used as `<HacktoberfestBadge year={2020} suggestionLabel='good first issue' />` to render to:

![GitHub Hacktoberfest combined status (suggestion label override)](https://img.shields.io/github/hacktoberfest/2020/dbartholomae/jsx-readme?suggestion_label=good%20first%20issue)

The badge needs to be exported from the [badges index barrel file](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/index.ts).
Please note that you will also have to provide test coverage and documentation for me to be able to accept the PR.

## Additional context

A good badge to base this new badge on is the [Codecov badge](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/CodecovBadge.tsx).

You can find out more about the badge on the [shields.io page](https://shields.io/category/issue-tracking). It is in the issue-tracking category as "GitHub Hacktoberfest combined status" and "GitHub Hacktoberfest combined status (suggestion label override)".

**Comment by kala2** [comment]
Hello, Is this available? I would love to take this!

**Comment by dbartholomae** [comment]
Yes. Please keep in mind that for this to count as part of Hacktober fest, the PR must be provided in October. I will also add more beginner-friendly issues over time, with the idea of giving multiple people the chance to get to know the repo.

**Comment by kala2** [comment]
Thanks, i'll keep in mind that!

**Comment by kala2** [comment]
Hello @dbartholomae,

Could you please assign the issue to me?
Submitted a PR, waiting for your review.
