### ISSUE TITLE
Add CLAAssistantBadge component

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#11]
Unfortunately, managing intellectual property nowadays is also an important part of open source. Fortunately, there are tools that help with this. [CLA Assistant](https://cla-assistant.io/) is one of them, and you will notice it latest when you open up your PR. They manage rights transfers. Let's add a badge to make it easy for open source maintainers to remain compliant.

This issue is meant to be a good first issue to get into this repository, and into open source contribution over all, as it will require to touch few existing files and is documented extensively. If this is your first contribution to open source, I encourage you to try this issue. Please note that I will only accept one of the good first issues per person to give as many people as possible the opportunity for a first contribution.

Please read our [contribution guidelines](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

## Describe the solution you'd like

This is what the badge should look like in its most basic form:

[![CLA assistant](https://cla-assistant.io/readme/badge/dbartholomae/jsx-readme)](https://cla-assistant.io/dbartholomae/jsx-readme)

It should be accessible as `<CLAAssistantBadge pkg={pkg} />`.

The badge needs to be exported from the [badges index barrel file](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/index.ts).
Please note that you will also have to provide test coverage and documentation for me to be able to accept the PR.

## Additional context

A good badge to base this new badge on is the [GitHub Workflow badge](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/GithubWorkflowBadge.tsx).

**Comment by anshdhinhgra47** [comment]
@dbartholomae Could you explain it in brief? I would like to work on this issue for hacktoberfest.

**Comment by anshdhinhgra47** [comment]
@dbartholomae I'd like to give this a shot! Could you assign it to me ?

**Comment by dbartholomae** [comment]
Sure! :)

**Comment by anshdhinhgra47** [comment]
Thanks for assigning me the issue!
Also, would it be okay if I make the PR on or after 1st October?

**Comment by dbartholomae** [comment]
Sure, no worries :)

**Comment by anshdhinhgra47** [comment]
Thank you :)

**Comment by anshdhinhgra47** [comment]
I am not able to link the tests, though I had run the npm test command

**Comment by dbartholomae** [comment]
If you are interested, I am [available for pair programming](https://calendly.com/bartholomae/open-source-pair-programming).

**Comment by anshdhinhgra47** [comment]
Sure, I have registered for the meeting. Thank you so much @dbartholomae

**Comment by dbartholomae** [comment]
Closed by #26
