### ISSUE TITLE
Add Setup Instructions Component

### ISSUE THREAD

**Issue by shakif95** [dbartholomae/jsx-readme#121]
**Is your feature request related to a problem? Please describe.**

** Would you be willing to help with a PR? **
- [ ] Yes, absolutely
- [x] Yes, with some guidance
- [ ] Unfortunately no time :'-(

## Describe the solution you'd like
A component that renders the `Setup instructions` section to the readme. For now, it is **limited to title only** and Similar to this:
```
## Set up instructions

Further descriptions here...
```

## Describe alternatives you've considered
N/A

## Additional context
The end result should be like this:

![image](https://user-images.githubusercontent.com/29252235/168060518-a8a2fec9-2df5-424e-89c0-9656f55ccd4f.png)

**Comment by dbartholomae** [comment]
Thanks! From a complexity perspective, I would not extract this into a component, but instead just use the Heading component.
