### ISSUE TITLE
Ideas welcome!

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#13]
As part of Hacktoberfest, this repository has been growing at a steady rate. If you have additional ideas of what we should add, feel free to open an issue and make a suggestion! There is a template for writing a feature suggestion, and there are plenty of issues already prepared you can read for inspiration.

Suggestions could include e. g.:
- Additional badges
- Additional README sections
- Additional templates for other markdown files

**Comment by dbartholomae** [comment]
Closing for now as Hacktoberfest has ended. Obviously, ideas are still welcome ;)

**Comment by junwen-k** [comment]
Greetings @dbartholomae, I am back for this year's Hacktoberfest! Just wondering if you have any ideas on mind to further improve this project? I would like to make some contributions to this project.

**Comment by dbartholomae** [comment]
I've reopened a couple of issues that still exist from last year. They are a bit more complicated than the average issue from last year, though.
