### ISSUE TITLE
Add ContributingSection component

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#14]
A CONTRIBUTING.md file is an established standard for communicating to contributors how to best contribute. But the first entry point to a repository is still the README file. Let's link them together with a section in the README.

This issue is meant to be a good first issue to get into this repository, and into open source contribution over all, as it will require to touch few existing files and is documented extensively. If this is your first contribution to open source, I encourage you to try this issue. Please note that I will only accept one of the good first issues per person to give as many people as possible the opportunity for a first contribution.

Please read our [contribution guidelines](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

## Describe the solution you'd like

The section should look like this:

```md
## Contributing

If you are interested in contributing to this repository, please read up on the details in our [contributing guidelines](./CONTRIBUTING.md).
```

It should be accessible as `<ContributingSection />`, with an optional prop `contributingFilePath` that can be used as `<ContributingSection contributingFilePath='./docs/CONTRIBUTING.md' />` to change the link.
The component also needs to be added to the end of the e2e test in `examples` and the corresponding expected file in `test` so that it shows up in this repo's README file.

The component needs to be exported from the [components index barrel file](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/index.ts).
Please note that you will also have to provide test coverage and documentation for me to be able to accept the PR.

## Additional context

A good badge to base this new badge on is the [GitHub Workflow badge](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/GithubWorkflowBadge.tsx).

A good example for a section is the [`HomepageFromPkg` component](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/HomepageFromPkg.tsx) and its [usage in the examples file](https://github.com/dbartholomae/jsx-readme/blob/main/examples/README.md.tsx#L55).

**Comment by dbartholomae** [comment]
Please note that this issue and #7 might be dependent on each other: If the other sections have emojis, this one should as well, but if #7 is not tackled yet, then this should also not have an emoji.

**Comment by hpnightowl** [comment]
Hi! @dbartholomae  can i take this issue as this will be my first issue ?

**Comment by dbartholomae** [comment]
@hpnightowl sure! :)

**Comment by AswinCG2002** [comment]
can i work on this as my first issue

**Comment by dbartholomae** [comment]
@AswinCG2002 currently it is assigned to @hpnightowl.
@hpnightowl When do you expect to work on it? If I don't hear back in the next couple days, I will have to open it up again.

**Comment by hpnightowl** [comment]
ya  i will work since it was of hacktoberfest issue so i have to do pr in oct that's why was off. today or tomorrow  i will pr

**Comment by dbartholomae** [comment]
Sounds great! :)

**Comment by hpnightowl** [comment]
anychanges needed do let me know :) @dbartholomae

**Comment by dbartholomae** [comment]
@hpnightowl Thanks for your contribution! The idea behind this issue is not to manually add a contributing section to this repo, but to write a component that can be used to automatically add a contribution section. I just saw that there was no good example yet of how to achieve this in the issue, so I've edited it and added an example file to the bottom of it.

**Comment by hpnightowl** [comment]
oh got it will soon do changes and push

**Comment by junwen-k** [comment]
Any update on this ? Can I work on this issue ?

**Comment by hpnightowl** [comment]
@junwen-k you can go on it

**Comment by hpnightowl** [comment]
@dbartholomae can you assign this issue to him?

**Comment by dbartholomae** [comment]
Sure :)
