### ISSUE TITLE
Add a LicenseBadge component

### ISSUE THREAD

**Issue by KwanJunWen** [dbartholomae/jsx-readme#19]
A GitHub repository can have a license badge rendered on top of the README.md to allow contributors / users to quickly understand which license the current project is using. 

## Would you be willing to help with a PR?
[X] Yes, absolutely
[ ] Yes, with some guidance
[ ] Unfortunately no time :'-(

## Describe the solution you'd like
This is what the badge should look like in its most basic form:

[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)

It should be accessible as `<LicenseBadge pkg={pkg} />`. 

Since Shields.io has autogenerated license badges: `https://img.shields.io/github/license/<Github-Username>/<Repository>`, perhaps the badge component will default to autogenerated license badges, and can have an optional prop that renders the appropriate license badge based on the `license` field on `package.json`.

## Additional context
The badges example and links can be found [here](https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba#file-license-badges-md).
For autogenerated sheilds badge, see [here](https://shields.io/category/license).

**Comment by dbartholomae** [comment]
I like it! If you want, feel free to go ahead :)

**Comment by dbartholomae** [comment]
Makes sense! Let's continue the rest of the discussion in the PR.
