### ISSUE TITLE
Add a CircleCIBadge component

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#2]
Some repositories use CircleCI for building. A badge showing the build status helps to understand whether the repo currently is in good shape.

This issue is meant to be a good first issue to get into this repository, and into open source contribution over all, as it will require to touch few existing files and is documented extensively. If this is your first contribution to open source, I encourage you to try this issue. Please note that I will only accept one of the good first issues per person to give as many people as possible the opportunity for a first contribution.

Please read our [contribution guidelines](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

## Describe the solution you'd like

This is what the badge should look like in its most basic form:

[![build status](https://circleci.com/gh/dbartholomae/middy-middleware-jwt-auth/tree/main.svg?style=shield)](https://circleci.com/gh/dbartholomae/workflows/middy-middleware-jwt-auth/tree/main)

It should be accessible as `<CircleCIBadge pkg={pkg} />`, with an optionals props `branch` and `style` (can only be "svg" or "shield") that can be used as `<CircleCIBadge pkg={pkg} branch='master' style='svg' />` to render to:

[![build status](https://circleci.com/gh/dbartholomae/middy-middleware-jwt-auth/tree/master.svg?style=svg)](https://circleci.com/gh/dbartholomae/workflows/middy-middleware-jwt-auth/tree/master)

The badge needs to be exported from the [badges index barrel file](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/index.ts).
Please note that you will also have to provide test coverage and documentation for me to be able to accept the PR.

If you are interested in an additional challenge, try to also support BitBucket and Gitlab in addition to GitHub, based on package.json

## Additional context

A good badge to base this new badge on is the [GitHub Workflow badge](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/GithubWorkflowBadge.tsx).

You can find out more about the badge on the [CircleCI docs page](https://circleci.com/docs/2.0/status-badges/).

**Comment by i-am-jeetu** [comment]
Hi @dbartholomae, I would like to work on this. Can you please assign me this?

**Comment by dbartholomae** [comment]
Sure! :)
