### ISSUE TITLE
Add a badge for Hits 

### ISSUE THREAD

**Issue by Ruchika30** [dbartholomae/jsx-readme#27]
**Is your feature request related to a problem? Please describe.**
A GitHub repository can have a HIT badge rendered on top of the README.md to allow contributors / users to quickly understand know how many people are viewing your GitHub projects!

** Would you be willing to help with a PR? **
[ ] Yes, absolutely

## Describe the solution you'd like
This is what the badge should look like in its most basic form:
## Hits
[![HitCount](http://hits.dwyl.io/tterb/Hyde.svg)](http://hits.dwyl.io/tterb/Hyde)

It should be accessible as 
`<HitsBadge username={username} project={project} />.`

Since Shields.io has autogenerated license badges: https://img.shields.io/github/license/<Github-Username>/<Repository>, perhaps the badge component will default to autogenerated license badges, and can have an optional prop that renders the appropriate license badge based on the license field on package.json.

**Comment by Ruchika30** [comment]
Hey @dbartholomae .How about this feature

**Comment by dbartholomae** [comment]
I like it! But please take a prop `pkg` and extract username and project from it. You will also have to handle the case where package.json does not contain the information by displaying an empty string. You can look at [GithubIssuesBadge](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/GithubIssuesBadge.tsx) as an example.
Please also remember to write a short documentation on what this badge does in the comment in front of the component. I had to look up the webpage to understand it.

```tsx
<HitsBadge pkg={pkg} />
```

**Comment by dbartholomae** [comment]
@Ruchika30 are you still working on this? Otherwise I would open it up on Friday :)

**Comment by Ruchika30** [comment]
> @Ruchika30 are you still working on this? Otherwise I would open it up on Friday :)

Yes @dbartholomae . I ll raise Pr soon

**Comment by Ruchika30** [comment]
@dbartholomae  KIndly review my PR https://github.com/dbartholomae/jsx-readme/pull/51

**Comment by dbartholomae** [comment]
Thanks! Looks good! 👍🏻 

Closed by #51
