### ISSUE TITLE
Add a CoverallsBadge component

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#3]
Some repositories use [Coveralls](https://coveralls.io/) for test coverage. A badge showing the current test coverage helps to understand whether the repo currently is in good shape.

This issue is meant to be a good first issue to get into this repository, and into open source contribution over all, as it will require to touch few existing files and is documented extensively. If this is your first contribution to open source, I encourage you to try this issue. Please note that I will only accept one of the good first issues per person to give as many people as possible the opportunity for a first contribution.

Please read our [contribution guidelines](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

## Describe the solution you'd like

This is what the badge should look like in its most basic form:

[![code coverage](https://coveralls.io/repos/github/dbartholomae/jsx-readme/badge.svg?branch=main)](https://coveralls.io/github/dbartholomae/jsx-readme?branch=main)

It should be accessible as `<CoverallsBadge pkg={pkg} />`, with an optionals props `branch` that can be used as `<CoverallsBadge pkg={pkg} branch='master' />` to render to:

[![code coverage](https://coveralls.io/repos/github/dbartholomae/jsx-readme/badge.svg?branch=master)](https://coveralls.io/github/dbartholomae/jsx-readme?branch=master)

The badge needs to be exported from the [badges index barrel file](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/index.ts).
Please note that you will also have to provide test coverage and documentation for me to be able to accept the PR.

If you are interested in an additional challenge, try to also support BitBucket and Gitlab in addition to GitHub, based on package.json

## Additional context

A good badge to base this new badge on is the [GitHub Workflow badge](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/GithubWorkflowBadge.tsx).

**Comment by erkska** [comment]
Hey! I would like to give this one a try also I won't make the PR before 1st October since I'm participating in Hacktoberfest.

**Comment by erkska** [comment]
nevermind, it's a bit over my head, sorry

**Comment by dbartholomae** [comment]
No worries. If you are interested, I'm happy to help :)

**Comment by MDShields7** [comment]
Hi Daniel, I am trying to figure out how to complete this task. I have some basic idea of how the typescript may be written, and haven't started that yet, I just want to attempt understand the whole process before diving in.

When you say I have to provide test coverage, does that mean writing tests first? Are there none yet?

Would the test coverage have to be sent to a third party before a badge can be created?

**Comment by dbartholomae** [comment]
You will only have to change files in the repository, everything else will be automatically one by the automation set up. Here's a recent PR that added another badge and shows how to write tests:
https://github.com/dbartholomae/jsx-readme/pull/23/files

The repository is always at 100% test coverage, so you will only have to add tests for the functionality that you are adding, not for other code.

**Comment by MDShields7** [comment]
If I allow branches in the Coveralls Badge Component:
1) The links to coveralls reporting pages can be shown, which is good
2) The badge can be shown, but may not be correct, which may be bad?

I don't know much about testing coverage, so I created my own example, called [coverall-reporting](https://github.com/MDShields7/coveralls-reporting), to explore Coveralls.
The [master branch](https://coveralls.io/github/MDShields7/coveralls-reporting) has 100% coverage and the [badge](https://coveralls.io/repos/github/MDShields7/coveralls-reporting/badge.svg?branch=master) shows it correctly at 100% coverage.
The [dev branch](https://coveralls.io/github/MDShields7/coveralls-reporting?branch=dev) has only 83% coverage, but the [badge](https://coveralls.io/repos/github/MDShields7/coveralls-reporting/badge.svg?branch=dev) still shows 100% coverage.

Would you like to show branches?

**Comment by MDShields7** [comment]
I have completed the badge component, although testing is not complete. I wanted to run the linter, and I run into this problem. 
```> eslint src/**/*.ts src/**/*.tsx examples/**/*.tsx test/**/*.tsx

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .

/Users/.../.../jsx-readme/examples/README.md.tsx
  61:6  error  Unsafe call of an any typed value  @typescript-eslint/no-unsafe-call```

You don't get this when you lint?

**Comment by dbartholomae** [comment]
You can ignore the warning, but the error in README.md.sx seems to be new. Looks like something that should be typed isn't.

**Comment by MDShields7** [comment]
After more Coveralls exploration, I found that the default Coveralls badge ( no branch specified in badge URL ) will show the latest master branch coverage report. This default badge shows even if the master has a lower coverage than another branch. So if a user doesn't put the branch like below, the default will be shown. **Readme.md.tsx** ```<CoverallsBadge pkg={pkg} branch={working} />```<br>  That seems to make sense to me, what do you think?

**Comment by dbartholomae** [comment]
In the `README.md.tsx` please don't add the badge as this repository is not using Coveralls, Sontheimern badge would be misleading.

**Comment by dbartholomae** [comment]
@MDShields7 I've explicitly assigned the issue to you as you are already working on it :)

**Comment by dbartholomae** [comment]
@MDShields7 are you still on this? Otherwise, I would unassign it again :)
