### ISSUE TITLE
Inconsistency of having <LineBreak>

### ISSUE THREAD

**Issue by junwen-k** [dbartholomae/jsx-readme#33]
Right now I've notice some inconsistency of rendering `<LineBreak>` internally. This results in making the generated result kind of unpredictable. In other words, should a component render an extra line break when used ?

For example: 
`<HomepageFromPkg />`

Should render 
```
## Homepage

You can find more about this on [https://dbartholomae.github.io/jsx-readme](https://dbartholomae.github.io/jsx-readme).
```
Or
```
## Homepage

You can find more about this on [https://dbartholomae.github.io/jsx-readme](https://dbartholomae.github.io/jsx-readme).
<-- Notice this extra line break here -->
```

** Would you be willing to help with a PR? **
[X] Yes, absolutely
[ ] Yes, with some guidance
[ ] Unfortunately no time :'-(

## Describe the solution you'd like
Should decide whether if rendering a section should include an extra line break and stick with the rule. Probably because `<HomepageFromPkg>` has an extra missing line break at the end.

## Additional Context

I've notice this issue while working on #14, will have to include an extra line break (double line breaks) if we stick to having an extra line break rule.

Components that include line break at the end:
1. `<CodeFile>` which is used in `<ExamplesFromPkg>`
1. `<DescriptionFromPkg>`

Components that does not include line break at the end: 
1. `<HomepageFromPkg>`

**Comment by dbartholomae** [comment]
Good point. Could you please suggest which components to adjust? Then we can align and you can implement it :)

**Comment by junwen-k** [comment]
If we would want to render an additional line break at the end of each section (`<ContributingSection>`, `<DescriptionFromPkg>`, `<ExamplesFromPkg>` and `<HomepageFromPkg>` ), then will need to update `<ContributingSection>` and `<HomepageFromPkg>`.

`<ExamplesFromPkg>` will render an additional line break by default because `<CodeFile>` will always render a line break.

You can see the inconsistency in `<DescriptionFromPkg>` which renders two line break.
```md
Some description about this package. <-- first line break -->
<-- second line break included in that component -->
```
And `<HomepageFromPkg>` which renders
```md
## Homepage <-- first line break by rendering <Heading> -->
<-- second line break by rendering <Heading> -->
You can find more about this on [homepage](homepage.html). <-- line break included tn that component, so that the component next to it will render directly on bottom of this text. -->
```

If we want we can stick to the principal like `<DescriptionFromPkg>` which by defaults render an additional line break, so that when u do 

```jsx
<DescriptionFromPkg />
```

**Comment by dbartholomae** [comment]
As a principle I would like to make sure that we can just put the section components in a file without additional linebreaks and it will render to nice markdown. So adding these LineBreaks sounds like a good idea :)
I've assigned the issue to you.
