### ISSUE TITLE
Add a GithubTopLanguageBadge component

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#4]
When trying to contribute to an open source repo, one of the first questions to answer is: Do I know the language needed for this repo? A simple badge can answer this question at the top of the README file.

This issue is meant to be a good first issue to get into this repository, and into open source contribution over all, as it will require to touch few existing files and is documented extensively. If this is your first contribution to open source, I encourage you to try this issue. Please note that I will only accept one of the good first issues per person to give as many people as possible the opportunity for a first contribution.

Please read our [contribution guidelines](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

## Describe the solution you'd like

This is what the badge should look like in its most basic form:

![GitHub top language](https://img.shields.io/github/languages/top/dbartholomae/jsx-readme)

It should be accessible as `<GithubTopLanguageBadge pkg={pkg} />`. It should also be added to the default badges used by [`BadgesFromPkg`](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/BadgesFromPkg.tsx) after the DevDependenciesBadge which would automatically include it also in this repos README. This means that you will also have to adjust the [expected result of the end-to-end test](https://github.com/dbartholomae/jsx-readme/blob/main/test/README.expected.md).

The badge needs to be exported from the [badges index barrel file](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/index.ts).
Please note that you will also have to provide test coverage and documentation for me to be able to accept the PR.

## Additional context

A good badge to base this new badge on is the [GitHub Workflow badge](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/GithubWorkflowBadge.tsx).

**Comment by KwanJunWen** [comment]
Can I work on this issue ? Thanks

**Comment by dbartholomae** [comment]
Sure :)

**Comment by KwanJunWen** [comment]
Created PR #12. This is my first pull request. Kindly review the PR, thank you. @dbartholomae

**Comment by dbartholomae** [comment]
Thanks a lot! Your component is now available as part of this package :)
