### ISSUE TITLE
Add a DiscordBadge

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#5]
Sometimes documentation isn't enough - you need to reach out to the community of an open source project to get help. But how to find them? If an open source project has a related Discord channel, this badge will help to promote it.

This issue is meant to be a good first issue to get into this repository, and into open source contribution over all, as it will require to touch few existing files and is documented extensively. If this is your first contribution to open source, I encourage you to try this issue. Please note that I will only accept one of the good first issues per person to give as many people as possible the opportunity for a first contribution.

Please read our [contribution guidelines](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

## Describe the solution you'd like

This is what the badge should look like in its most basic form:

[![Discord](https://img.shields.io/discord/750063320614174871)](https://discord.gg/X9HRSK5)

It should be accessible as `<DiscordBadge serverId={750063320614174871} inviteLink='https://discord.gg/X9HRSK5' />`.

The badge needs to be exported from the [badges index barrel file](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/index.ts).
Please note that you will also have to provide test coverage and documentation for me to be able to accept the PR.

## Additional context

A good badge to base this new badge on is the [JSXReadmeBadge](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/JsxReadmeBadge.tsx).

You can find out more about the badge on the [shields.io page](https://shields.io/category/chat). It is in the chat category as "Discord".

**Comment by Ruchika30** [comment]
Hello @dbartholomae .This would be my first issue. Can I take it up?

**Comment by dbartholomae** [comment]
Sure! :)

**Comment by Ruchika30** [comment]
Hello @dbartholomae . I have cloned the [jsx-readme]( https://github.com/dbartholomae/jsx-readme.git) repo. And I need to add the discord badge like the other badges that I are visible (eg: npm pakges, downloads etc). This is my understanding . Please correct me if wrong.

**Comment by dbartholomae** [comment]
You will need to create a `DiscordBadgd` component similar to the `JSXReadmeBadge` component. You can also have a look at some of the recent PRs for inspiration, they also added new badge components.

**Comment by Ruchika30** [comment]
PRS=s of which repo @dbartholomae . I couldn't see any in jsx-readme.

**Comment by dbartholomae** [comment]
They are closed. When you go to the PRs tab, you will see that by default you only see PRs that are still open (`is:open`). You can either deleted that from the filters field or click "4 Closed" to show all closed PRs.

**Comment by Ruchika30** [comment]
@dbartholomae How do I run the project. From readMe I understand that it can be added in dev-dependency & used. Is it the only way I test it ?

**Comment by dbartholomae** [comment]
Have you already checked our [contributing guidelines](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md)? There is a section called "Set up instructions" that hopefully answers your questions :)

**Comment by Ruchika30** [comment]
@dbartholomae I am trying to commit my changes. But somehow I am failing every time. It says, subject may not be empty, type may not be empty.

Below is my commit message . Also I tried entering the same in different lines in the editor by doing 'git commit -a'. But that did not help too 

`git commit -m "DiscordBadge Addition"&'\n'"This commit adds a new discordBadge which will redirect the user to the platform for discussion"&'\n'"This new badge is accessible as <DiscordBadge pkg={pkg}>"`

Could you pls tell me where I am going wrong

**Comment by dbartholomae** [comment]
Sure! We are using [conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) in this project which are used to automatically create a changelog out of. You can also look through the commit messages in the other PRs or the rest of the repo to see the style :)

**Comment by Ruchika30** [comment]
Hey @dbartholomae . The test for creating README file of the repo has been failing  stating "fork failed". No other details. Can u pls assist for what reason it must be going wrong

**Comment by Ruchika30** [comment]
Hello  @dbartholomae . requesting you to kindly check the latest  commit on the Pr. (feat: rremoved default values )

**Comment by dbartholomae** [comment]
Closed by #21

**Comment by Ruchika30** [comment]
hey @dbartholomae .Can this be counted towards hacktoberfest. ?

**Comment by dbartholomae** [comment]
Just checked and it seems only PRs that are created in October can be counted :(
Nothing I can do about it, maybe ask the Hacktoberfest team?

**Comment by Ruchika30** [comment]
No problem. Thanks. I will work on more
