### ISSUE TITLE
Add Optional Emoji props

### ISSUE THREAD

**Issue by KwanJunWen** [dbartholomae/jsx-readme#52]
Some users might not want an emoji generated on each of the section header.

## Describe the solution you'd like
Add `disableEmoji` prop on each components that render emoji by default.

For example: 
```jsx
<ExamplesFromPkg disableEmoji />
```

## Describe alternatives you've considered
Having the need to pass in `disableEmoji` prop to each of the components that render emoji by default might seem a bit tedious.
Perhaps having something similar to React context, that you can disable the entire Readme from generating emojis just by setting `disableEmoji` once on the provider. But not sure if this is doable and is probably over complicated for this use case.

**Comment by dbartholomae** [comment]
Instead how about an optional "title" prop to override the full title?

**Comment by KwanJunWen** [comment]
Yup that could be the solution as well. Users can also provide the full title in different languages. Should we include a `description` prop that changes the content of the section as well ? But this kinda defeats the purpose of convenient components. Perhaps `description` props is not necessary at the moment.

As a side note, do you think in the future we could support more languages or do you think it is out of the scope of this package ?

**Comment by dbartholomae** [comment]
I would say that for now multiple languages are out of scope.

**Comment by KwanJunWen** [comment]
Noted. You could assign someone else to work on this issue, would like to give more opportunity for everyone to work on this issue. If there's no one else, I can work on it :)

**Comment by Ruchika30** [comment]
Hey @dbartholomae .I tried to work on it . Kindly check my PR https://github.com/dbartholomae/jsx-readme/pull/55 for the same

**Comment by dbartholomae** [comment]
Closed by #56

**Comment by dbartholomae** [comment]
Thanks @Ruchika30 ! :)
