### ISSUE TITLE
Add initialization script

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#6]
When using jsx-readme for the first time, you need to create a `README.md.tsx` file and set up `ts-node` to run it. This is not a huge burden - but we can do better! Instead it should be possible to just run `jsx-readme init` and it automatically does it for you.

This issue is a bit more complicated than the other issues provided for Hacktoberfest. If you struggle with it, feel free to try an issue labelled `good first issue` first. If you want to give it a try, I am happy to help with this though and might even be available to pair program on it.

Please read our contribution guidelines before picking this up, it will also lead you through the process of setting up the repository.

## Describe the solution you'd like

Please add a script that creates a `README.md.tsx` file, adds `ts-node` as devDependency if needed and adds a `docs` script to run the `README.md.tsx` file with `ts-node` if there is no `docs` script yet. There should be an example bash file how to invoke the script:

```sh
npx jsx-readme init
```

This file should be invoked in an e2e test to ensure it does what it is supposed to do.

The `README.md.tsx` file should be similar to [the one used for creating this repo](https://github.com/dbartholomae/jsx-readme/blob/main/examples/README.md.tsx), but without the custome installation section.

Please update the installation section in the [README.md.tsx](https://github.com/dbartholomae/jsx-readme/blob/main/examples/README.md.tsx) used for creating the README of this repo based on the new script. Please note that you will also have to update the [expected result for the related e2e test](https://github.com/dbartholomae/jsx-readme/blob/main/test/README.expected.md).

Please make sure to also update the [`bin` entry of `package.json`](https://docs.npmjs.com/files/package.json#bin).

If you get stuck working on this, I am [available for pair programming](https://calendly.com/bartholomae/open-source-pair-programming).

**Comment by SkullCarverCoder** [comment]
Hi I would love to work on this if possible, I have experience with both Typescript and React as well as developing scripts (not only python but on node) and CLIs (It is in the realm of possibility creating a CLI) I would for the user if expressed in a parameter for the basic text/sections to be included in the `README.md.tsx` file, or even I could read an existing `README.md` file in the project folder and extract data from there 😁 and of course all with it's proper tests.

**Comment by dbartholomae** [comment]
Thanks! I will assign the issue to you :)
Concerning the CLI I would suggest to keep it simple: rather than having to learn CLI options, the users should just edit the README.md.tsx that is created directly, and instead of the script customizing the README.md.tsx based on the repo, the file should use components that customize their own result.

**Comment by SkullCarverCoder** [comment]
Got it, I'll start working this week on this, hopefully you'll assign it to me and you'll see the pull request on the weekend, next week tops. 😁👌

**Comment by dbartholomae** [comment]
@SkullCarverCoder How's it going? :)

**Comment by SkullCarverCoder** [comment]
@dbartholomae greetings , I'm sorry for not following up on the changes , was sick with symptoms of COVID from October 19 until pretty much this weekend (No public wide testing in my third world country of Venezuela so just assumed I got it), so I was bedridden and in self-quarantine . This weekend I'll put up the changes with no more delays. Hope you are ok and well

**Comment by dbartholomae** [comment]
Thanks, all the best, and don't feel pressured - if you have other things to catch up on first, they most likely are more important :)

**Comment by dbartholomae** [comment]
Opened up again for Hacktoberfest 2021
