### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by jruipinto** [dbartholomae/jsx-readme#60]
This project is awesome but it took me more than 2 hours to understand how to build my README file with jsx-readme because the installation instructions aren't clear (at least to me, they are not).

** Would you be willing to help with a PR? **
- [x] Yes, absolutely
- [ ] Yes, with some guidance
- [ ] Unfortunately no time :'-(

## Describe the solution you'd like
The installation instructions should provide all the steps for at least 1 of the ways to build README with ts-node.

## Describe alternatives you've considered
Does not apply

## Additional context
I think installation instructions would be more helpfull if they were like this:

Installation

Add  `jsx-readme` and `ts-node` to your devDependencies
```sh
npm i jsx-readme ts-node -D
```

Add these  configs to your `tsconfig.json`:
```json
{
  "compilerOptions": {
    "resolveJsonModule": true,
    "jsx": "react"
   }
}
```

Create a README.MD template (you may copy the example from this repo `examples/README.md.tsx` and edit to your taste).

Add the following script to your `package.json`:

```json
{
  "scripts": {
    "generate:readme": "ts-node README.md.tsx"
  }
}
```

**Comment by dbartholomae** [comment]
Happy to accept a PR! The original idea was to add a script that could be used to automate all of this, but the script never got finished (#6).
Please keep in mind that the README in this repo is built from https://github.com/dbartholomae/jsx-readme/blob/main/examples/README.md.tsx, and you will also have to update the related test fixture https://github.com/dbartholomae/jsx-readme/blob/main/test/README.expected.md

**Comment by jruipinto** [comment]
I´m having problems placing multi-line code examples. Can you suggest something @dbartholomae ?

**Comment by dbartholomae** [comment]
Where do you mean? If it's for a PR to this repo, feel free to create the PR and I can help there :)
