### ISSUE TITLE
Add emojis to section headings

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#7]
A README shouldn't only be readable, but also nice to look at. So let's add some nice looking emoji! 🥳

This issue is meant to be a good first issue to get into coding, and into open source contribution over all, as it will require to touch few existing files, is a small change and is documented extensively. If you are new to coding, I encourage you to try this issue. Please note that I will only accept one of the good first issues per person to give as many people as possible the opportunity for a first contribution.

Please read our [contribution guidelines](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

## Describe the solution you'd like

The [`ExamplesFromPkg`](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/ExamplesFromPkg.tsx) and [`HomepageFromPkg`](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/HomepageFromPkg.tsx) components create headings. Let's start each of them with a fitting emoji. You will have to also adjust the corresponding [test](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/ExamplesFromPkg.test.tsx) [files](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/HomepageFromPkg.test.tsx).

In addition, we manually create an installation section in our [e2e test](https://github.com/dbartholomae/jsx-readme/blob/main/examples/README.md.tsx). We should find a nice emoji for this paragraph as well. You will have to also adjuts the corresponding [expected output file](https://github.com/dbartholomae/jsx-readme/blob/main/test/README.expected.md).

## Additional context

When choosing emojis, please use utf-8 emojis that can be copied directly into the source code instead of images. Please keep in mind cultural implications and try to choose emojis that will appeal universally.
You can find utf-8 emojis e. j. on [getemoji.com](https://getemoji.com/).

If you get stuck working on this, I am [available for pair programming](https://calendly.com/bartholomae/open-source-pair-programming).

**Comment by outofgamut** [comment]
I'll take this one!

**Comment by dbartholomae** [comment]
Hi @outofgamut, I would love to keep this issue open for contributors who don't have much coding experience yet.

**Comment by kishanhitk** [comment]
Hi @dbartholomae, I would like to work on it. This will be my first contribution.

**Comment by dbartholomae** [comment]
Hi @kishanhitk, as mentioned I would like to keep this issue for people with little coding experience as it can be done even if you have just started coding yesterday. There is plenty other issues though for everyone with coding experience, though, in different levels of complexity :)

**Comment by AJMcDee** [comment]
Hi! I saw this linked from Discord. I'd love a chance to work on this. I'm studying web development at the moment so although I've done some of my own projects before, I have very limited experience working with other projects. It would be great to give this a go in collaboration with you :)

**Comment by dbartholomae** [comment]
@AJMcDee Happy to have you here! :)

**Comment by AswinCG2002** [comment]
hey, i would love to work on this.would u pls assign me this

**Comment by dbartholomae** [comment]
Sure :)

**Comment by dbartholomae** [comment]
@AswinCG2002 Sorry, it is already assigned to @AJMcDee

**Comment by dbartholomae** [comment]
@AJMcDee how's it going? Do you want to continue on this? Otherwise I would open it up again on Friday :)

**Comment by AJMcDee** [comment]
Hi! I have some time today so will look at it now. Thank you for your patience :)

**Comment by dbartholomae** [comment]
Thanks! Did not want to pressure you, just want to make sure everyone who is interested gets a chance to work on issues in this repository :)
