### ISSUE TITLE
Add NpmBundleSizeBadge component

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#8]
When using a dependency in frontend or in a system where bootup times are critical (e. g. AWS lambda), the size of each dependency counts. Fortunately, there is [Bundlephobia](https://bundlephobia.com/), which tells you how many KB (or even MB?) you will be adding with a new dependency. Let's add a badge for it!

This issue is meant to be a good first issue to get into this repository, and into open source contribution over all, as it will require to touch few existing files and is documented extensively. If this is your first contribution to open source, I encourage you to try this issue. Please note that I will only accept one of the good first issues per person to give as many people as possible the opportunity for a first contribution.

Please read our [contribution guidelines](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

## Describe the solution you'd like

This is what the badge should look like in its most basic form:

[![npm bundle size](https://img.shields.io/bundlephobia/minzip/jsx-readme)](https://bundlephobia.com/result?p=jsx-readme)

It should be accessible as `<NpmBundleSizeBadge pkg={pkg} />`. It should also be added to the default badges used by [`BadgesFromPkg`](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/BadgesFromPkg.tsx) after the NpmDownloadsBadge which would automatically include it also in this repos README. This means that you will also have to adjust the [expected result of the end-to-end test](https://github.com/dbartholomae/jsx-readme/blob/main/test/README.expected.md).

The badge needs to be exported from the [badges index barrel file](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/index.ts).
Please note that you will also have to provide test coverage and documentation for me to be able to accept the PR.

## Additional context

A good badge to base this new badge on is the [NpmVersion badge](https://github.com/dbartholomae/jsx-readme/blob/main/src/components/badges/NpmVersionBadge.tsx).

You can find out more about the badge on the [shields.io page](https://shields.io/category/size). It is in the size category as "npm bundle size".

**Comment by tancredosouza** [comment]
Hello there! Hope this message finds you well.
Could I try this one?

**Comment by dbartholomae** [comment]
Sure! :)

**Comment by dbartholomae** [comment]
Just realized there is a mistake in the ticket: The badge should link to Bundlephobia. Will update it asap :)

**Comment by dbartholomae** [comment]
Updated.

**Comment by tancredosouza** [comment]
Hi! I think I've almost got it. 

I'm unable to generate a new `./README.md` to compare with the new `./test/README.expected.md`.

Should I change these files manually? I was expecting I could run some terminal command on the repo to create another README.md, with the new `NpmBundleSizeBadge`.

**Comment by dbartholomae** [comment]
You might need to run `npm build` and then run the test in `./test/README.md.test.tsx`. I will update the `npm test` shortly so that it takes care of building in the future.

**Comment by tancredosouza** [comment]
Thanks! That did change the `README.md` automatically. 
However, `README.expected.md` is still the same (i.e. does not expect a `NpmBundleSizeBadge`. Should I then update this file manually?

**Comment by dbartholomae** [comment]
Yes, this needs to be automated manually to make sure it is the change you want.

**Comment by tancredosouza** [comment]
Thanks for all the help! This was really fun.
I have created a pull request (#10) but wasn't able to add you as a reviewer.

I'll stay put for any improvements you might suggest! 😀

**Comment by dbartholomae** [comment]
Thanks a lot! It was a pleasure to have you contribute! :)
