### ISSUE TITLE
Add ContributingFile component

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-readme#9]
When contributing to open source projects, a significant amount of time can be lost when setting up the repo locally and understanding the coding standards used in that repository. A good CONTRIBUTING.md file can help. Let's make it easier to add one.

This issue will take a bit longer than the other issues set up for Hacktoberfest, but it should not be too complicated. If you are interested in deeper contributions into the repository, I would recommend taking a small [good first issue](https://github.com/dbartholomae/jsx-readme/labels/good%20first%20issue) first and then take on this one. If you are already quite familiar with software development, this might also be an interesting starting point for the repository.

## Describe the solution you'd like

Create a ContributingFile component that renders to markdown similar to this repo's [CONTRIBUTING.md](https://github.com/dbartholomae/jsx-readme/blob/main/CONTRIBUTING.md) based on a `package.json` input as `pkg` prop. The file should be constructed based on the actual tooling, e. g. if `yarn` is used as the package manager (as can be obvious from a `yarn.lock` file), then the installation instructions should be talking about `yarn` instead of `pnpm`, or if `istanbul` is not used for code coverage, then adding a `/* istanbul ignore next */` comment won't make sense. Also, please don't hardcode my email address as the security contact, and use a prop to set the correct email address instead ;)

It might make sense to split the component into a pure display component taking data as props, and a container component reading the needed data from package.json or the file system.

I'm open to already merging smaller versions with less functionality, as long as the component is overall useable. The goal should be to automatically build the CONTRIBUTING.md of this repository, similar to how the README.me is built.

If you get stuck working on this, I am [available for pair programming](https://calendly.com/bartholomae/open-source-pair-programming).

**Comment by taksuparth** [comment]
This looks interesting! I would like to give it a shot

**Comment by dbartholomae** [comment]
Great! :)

**Comment by taksuparth** [comment]
Hey @dbartholomae! I've created the component `ContributingFile` and it is generating readme the same as your `CONTRIBUTION.md`. In the configuration, I am taking `email` field in `pkg` prop (which we are getting from package.json).

Now, for the second part, I am a little confused as to how should I approach it? Because `yarn` or `npm` or `pnpm` are std. package manager. One can choose them interchangeably, the only way to know about which package manager project is using is by checking the existence of `yarn.lock` or `pnpm-lock.yml`. How will the component get this information in `package.json`? Either we should include a flag inside package.json which will be used to generate CONTRIBUTION.md or we should add a package-manager flag as prop to the component.

**Comment by dbartholomae** [comment]
For now the component can use the synchronous file reading API from `fs`.

**Comment by dbartholomae** [comment]
I would suggest though to split into two levels: One component that is pure and takes the info as props, and another components that gets both info (pkg file and package manager) by reading the file system.

**Comment by taksuparth** [comment]
Hey @dbartholomae! Sorry, I got caught up with one of my projects for last 2 weeks, just got free. I will start working on this from tomorrow and hopefully, I will have substantial to show this weekend :)

**Comment by dbartholomae** [comment]
@taksuparth how's it going? :)

**Comment by dbartholomae** [comment]
Opened for Hacktoberfest 2021

**Comment by dbartholomae** [comment]
Please note the work that has already been done:
https://github.com/dbartholomae/jsx-readme/pull/88
