### ISSUE TITLE
Add AuthorSection component

### ISSUE THREAD

**Issue by junwen-k** [dbartholomae/jsx-readme#93]
Sometimes having an Author section on the README file might help. Let's automate this process.

## Describe the solution you'd like
To display an Author section inferred by package.json. The component should support both the object and the string syntax. See https://docs.npmjs.com/cli/v7/configuring-npm/package-json#people-fields-author-contributors.

The component should also be able to receive a name prop which changes the output. E.g, `package`, `library`. The email part is optional.

```tsx
<AuthorSection pkg={pkg} name="package" />
```

## Describe alternatives you've considered
We can also introduce a generic component which takes in person in object or string format and output a generic profile markup. This way we can potentially reuse this component for contributors or even maintainers from package.json.

## ✍️ Author

This package is written with love by **[dbartholomae](https://github.com/dbartholomae)**. For more info, you can reach the author [via email](mailto:info@bartholomae.name).

**Comment by dbartholomae** [comment]
Thanks! What would this look like in markdown?

**Comment by junwen-k** [comment]
I've updated my issue content :)

**Comment by dbartholomae** [comment]
Thanks! To be honest, given that we already have Contributors, I don't think this will be that relevant.
