### ISSUE TITLE
Add FundingSection component

### ISSUE THREAD

**Issue by junwen-k** [dbartholomae/jsx-readme#94]
We can automate a funding section by inferring package.json.

## Describe the solution you'd like
Create a component that renders a funding section inferred in package.json.

```tsx
<FundingSection pkg={pkg} />
```

## 🤝 Show your support

Give a ⭐ if this package helped you! You can also support the development of this package by funding.

- [example](http://example.com/donate)
- [patreon](https://www.patreon.com/my-account)

**Comment by dbartholomae** [comment]
Thanks! What would this look like in markdown?

**Comment by dbartholomae** [comment]
Looks good, let's get a first version out with the list, and maybe we can add buttons in an update in the future.
